### PR TITLE
Rerendered Using Grayskull - v1.21.0

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@marcelotrevisani could you please review and merge. This is a pre-requisite for 
  - https://github.com/conda-forge/opentelemetry-exporter-otlp-proto-common-feedstock/pull/8
 Please let me know - if you would like me to add myself as a maintainer to this repo too

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani could you please review and merge. This is a pre-requisite for
> 
> * [Rerendered Using Grayskull - v1.21.0 opentelemetry-exporter-otlp-proto-common-feedstock#8](https://github.com/conda-forge/opentelemetry-exporter-otlp-proto-common-feedstock/pull/8)
>   Please let me know - if you would like me to add myself as a maintainer to this repo too

hey, I am not the maintainer of this feedstock, @mariusvniekerk is the maintainer. :)
If he does not answer in a couple days ping me again and we will get it sorted 😄

**Comment by rxm7706** [comment]
Hi @marcelotrevisani
Sorry about that - Auto Complete failed me there !
Could you please approve starting with this
https://github.com/conda-forge/opentelemetry-semantic-conventions-feedstock/pull/27
So that we can merge 
https://github.com/conda-forge/opentelemetry-exporter-otlp-proto-common-feedstock/pull/8 &
https://github.com/conda-forge/opentelemetry-proto-feedstock/pull/23 (this PR)

I've made a list of all the updates needed - there seem to about 40+ recipes that need to refreshed and updated
https://github.com/conda-forge/opentelemetry-sdk-feedstock/pull/31

```
Updates Needed

    https://github.com/conda-forge/opentelemetry-sdk-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-proto-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-exporter-jaeger-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-exporter-otlp-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-exporter-otlp-proto-common-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-exporter-otlp-proto-grpc-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-exporter-otlp-proto-http-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-exporter-opencensus-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-semantic-conventions-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-aiohttp-client-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-aiopg-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-asgi-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-asyncpg-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-boto-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-botocore-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-celery-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-dbapi-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-django-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-elasticsearch-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-falcon-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-fastapi-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-flask-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-grpc-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-jinja2-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-logging-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-mysql-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-psycopg2-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-pymemcache-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-pymongo-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-pymysql-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-pyramid-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-redis-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-requests-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-sklearn-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-sqlalchemy-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-sqlite3-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-starlette-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-tornado-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-urllib-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-urllib3-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-instrumentation-wsgi-feedstock/blob/main/recipe/meta.yaml
    https://github.com/conda-forge/opentelemetry-distro-feedstock/blob/main/recipe/meta.yaml
```

**Comment by rxm7706** [comment]
Superceeded by https://github.com/conda-forge/opentelemetry-proto-feedstock/pull/26

**Pull request closed without merging**
